---
name: "IPTV"
guid: "a59b5c4b-05a8-488f-bfa8-7a63fffc7639"
version: "5.0.0.0"
targetAbi: "10.5.0.0"
owner: "jellyfin"
overview: "Enable IPTV support in Jellyfin"
description: "Enable IPTV support in Jellyfin"
category: "Channel"
artifacts:
- "MediaBrowser.Channels.IPTV.dll"
changelog: >
  changelog
